apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: parlacards-hrastnik
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  tls:
    - hosts:
        - parlacards-hrastnik.lb.djnd.si
      secretName: parlacards-hrastnik-tls
  rules:
    - host: parlacards-hrastnik.lb.djnd.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: parlacards-hrastnik
                port:
                  number: 3000
