apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: parlacards-hrastnik
    newName: rg.fr-par.scw.cloud/djnd/parlacards-hrastnik
    newTag: 'latest'
