apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-hrastnik
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: parlacards-hrastnik
    newName: rg.fr-par.scw.cloud/djnd/parlacards-hrastnik
    newTag: 'b21125253305c166e43d128650be4d1a38399692'
