apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: parlacards
    newName: rg.fr-par.scw.cloud/djnd/parlacards
    newTag: 'f9a4c541cc0c2545ea0a0ed4d6cf43293656c43f'
