apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-ajdovscina
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: parlacards-ajdovscina
    newName: rg.fr-par.scw.cloud/djnd/parlacards-ajdovscina
    newTag: '941c5990ef568546e1994cded3102c8679d55fbd'
