apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-ajdovscina
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: parlacards-ajdovscina
    newName: rg.fr-par.scw.cloud/djnd/parlacards-ajdovscina
    newTag: 'a0ace9e5c47c38691696ed2a6426d3bc2261b4c4'
