apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-ua
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: parlacards-ua
    newName: rg.fr-par.scw.cloud/djnd/parlacards-ua
    newTag: '49a22d755d50c93416defa263c295af237d0ae31'
