apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-ua
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: parlacards-ua
    newName: rg.fr-par.scw.cloud/djnd/parlacards-ua
    newTag: '70cdee9d7920c344f00c7b5348ca359794f0c3fa'
