apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-lendava
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: parlacards-lendava
    newName: rg.fr-par.scw.cloud/djnd/parlacards-lendava
    newTag: 'abcdd77dfc908468df5b0b87fcadc5816ce9bb56'
