apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: parlacards
    newName: rg.fr-par.scw.cloud/djnd/parlacards
    newTag: '657abff12a9f2dcc0a3ece40da2c12f29cfc2952'
